### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by PalchikV** [3liz/lizmap-locales#13]
Good afternoon. We have translated the LIZMAP project into Ukrainian on the transifex.com resource. Could you add Ukrainian (Ukraine) (uk_UA) localization to the repository?

**Comment by Gustry** [comment]
I'm keeping the ticket open for the Jelix side, CF comment in #14. This PR was covering only the LWC side.

**Comment by Gustry** [comment]
> Should we move Jelix to (uk_UA) first, and then localization will be added in the update?

I'm not sure to understand.
Please read https://github.com/3liz/lizmap-web-client/blob/master/CONTRIBUTING.md#localization
Both projetcs must be translated if you want a UI 100% translated. LWC and Jelix.

**Comment by Gustry** [comment]
Translations (both Jelix and LWC) has been added in the Lizmap Web Client.
Thanks for your contribution.

**Comment by PalchikV** [comment]
Thank you. Thank you for your work too

**Comment by PalchikV** [comment]
I'm sorry, but I don't see the following data
 (admin/locales) and (view/locales)
Will you add them?

**Comment by Gustry** [comment]
We are releasing LWC 3.4 this afternoon, all commits are there :  
- https://github.com/3liz/lizmap-web-client/commits/release_3_4
- https://github.com/3liz/lizmap-locales/commits/lizmap_3_4

**Comment by PalchikV** [comment]
Good afternoon. I will repeat the question. Will the following files be added to Ukrainian localization?
I don't see the following data
(admin/locales) and (view/locales)
Will you add them?

**Comment by Gustry** [comment]
I already answered you in my previous comment : 
* LWC 3.4 https://github.com/3liz/lizmap-web-client/tree/release_3_4/lizmap/app/locales/uk_UA everything is here
* LWC 3.5 https://github.com/3liz/lizmap-web-client/tree/release_3_5/lizmap/app/locales/uk_UA everything is here*
* LWC 3.6 not done because we don't have any release planned for now

> (admin/locales) and (view/locales)

Which folder are you looking at ? In your local folder or on GitHub ? Which branch (3.4, 3.5, 3.6) ? Do you have an URL ?

**Comment by PalchikV** [comment]
Saw everything. Sorry to disturb you.
Thank you)
Have a good day)

**Comment by Gustry** [comment]
No worries !
